title: Conner Hoffman Portfolio
author: Conner Hoffman
email: connerhoff@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Conner Hoffman
  tagline: System Administrator. Cyber Security Researcher. Ethical Hacker
  date_format: #"%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: sudodl09
  #  github:  Connerh6
    linkedIn: in/conner-hoffman-387059174
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages: about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
